name: BrokenSpeedruns
version: 1.2.1
main: com.wilder0p.speedrun.BrokenSpeedruns
api-version: 1.21
commands:
  speedrun:
    description: Start a solo Any% speedrun or manage it
    usage: /speedrun [start [classic|horror]|quit|restart|list|top [horror]|help]
